[package]
name = "im"
version = "12.2.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
license = "MPL-2.0+"
description = "Immutable collection datatypes"
repository = "https://github.com/bodil/im-rs"
documentation = "http://immutable.rs/"
homepage = "http://immutable.rs/"
readme = "./README.md"
categories = ["data-structures"]
keywords = ["immutable", "persistent", "hamt", "b-tree", "rrb-tree"]
build = "./build.rs"
exclude = ["dist/**", "rc/**", "release.toml", "Makefile.toml", "proptest-regressions/**"]

[lib]
path = "./src/lib.rs"

[badges]
travis-ci = { repository = "bodil/im-rs" }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docs_rs_workaround"]

[build-dependencies]
rustc_version = "0.2"

[dependencies]
typenum = "1.10"
quickcheck = { version = "0.7", optional = true }
proptest = { version = "0.8", optional = true }
serde = { version = "1.0", optional = true }
rayon = { version = "1.0", optional = true }

[dev-dependencies]
proptest = "0.8"
serde = "1.0"
serde_json = "1.0"
rayon = "1.0"
rand = "0.6"
pretty_assertions = "0.5"
