[package]
name = "im"
version = "5.0.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
license = "LGPL-3.0+"
description = "Assorted immutable collection datatypes"
repository = "https://github.com/bodil/im-rs"
documentation = "https://docs.rs/im/"
readme = "README.md"
categories = ["data-structures"]
keywords = ["immutable", "persistent"]

[badges]
travis-ci = { repository = "bodil/im-rs" }

[dependencies]
quickcheck = { version = "0.4", optional = true }
proptest = { version = "0.1", optional = true }

[dev-dependencies]
quickcheck = "0.4"
proptest = "0.1"
rand = "0.3"
