[package]
name = "im"
version = "10.2.1-alpha.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
license = "MPL-2.0+"
description = "Assorted immutable collection datatypes"
repository = "https://github.com/bodil/im-rs"
documentation = "http://immutable.rs/"
homepage = "http://immutable.rs/"
readme = "README.md"
categories = ["data-structures"]
keywords = ["immutable", "persistent"]
build = "build.rs"

[badges]
travis-ci = { repository = "bodil/im-rs" }

[build-dependencies]
rustc_version = "0.2"

[dependencies]
quickcheck = { version = "0.6", optional = true }
proptest = { version = "0.7", optional = true }
serde = { version = "1.0", optional = true }
clippy = { version = "0.0", optional = true }

[dev-dependencies]
quickcheck = "0.6"
proptest = "0.7"
serde = "1.0"
serde_json = "1.0"
rand = "0.4"
pretty_assertions = "0.5"
